name: ayon-hibob-services
services:
  syncservice:
    container_name: ayon-hibob-sync
    image: ynput/ayon-hibob-sync:1.0.0
    restart: unless-stopped
    environment:
      - "AYON_SERVER_URL=${AYON_SERVER_URL}"
      - "AYON_API_KEY=${AYON_API_KEY}"
      - "AYON_ADDON_VERSION=${AYON_ADDON_VERSION}"
      - "AYON_ADDON_NAME=hibob"
